version: "3.9"
   
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
     - "5432:5432"
  web:
    image: zhanlederzach/sa-homework-api-test:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres 
