apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-config
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
type: Opaque
data:
  POSTGRES_DATABASE: cG9zdGdyZXMK
  POSTGRES_USERNAME: cG9zdGdyZXMK
  POSTGRES_PASSWORD: cG9zdGdyZXMK
